name: fitness_ui
description: "A new Flutter project."
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  fitness_app:
    path: ../fitness_app
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_zoom_drawer: ^3.1.1
  intl: ^0.18.1
  shimmer: ^3.0.0
  intl_utils: ^2.8.7

dev_dependencies:
  

flutter:
  uses-material-design: true
  generate: true

  # This is folder for assets: image, icon in the app.
  assets:
    - assets/images/
    - assets/icons/

  # This is for custom two fonts in the app.
  fonts:
    - family: Bebas-Regular
      fonts:
        - asset: assets/fonts/Bebas-Regular.otf
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

# Config i18n generation
flutter_intl:
  enabled: true
  class_name: FAUiS
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  main_locale: vi
  
