name: flutter_practice_one
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  fitness_ui:
    path: ../fitness_ui
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_zoom_drawer: ^3.1.1
  go_router: ^12.1.3

dev_dependencies:
  device_preview: ^1.1.0
  provider: ^6.1.1

  # This package provides lint rules for Dart and Flutter which are used at Very Good Ventures.
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  # This is folder for assets: image, icon in the app.
  assets:
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/
    - assets/icons/

  # This is for custom two fonts in the app.
  fonts:
    - family: Bebas-Regular
      fonts:
        - asset: assets/fonts/Bebas-Regular.otf
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
